language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

# PostGIS Support Matrix: https://trac.osgeo.org/postgis/wiki/UsersWikiPostgreSQLPostGIS
env:
  - DOCTRINE_VERSION=~2.4.0 POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=1.5
  - DOCTRINE_VERSION=~2.4.0 POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.0
  - DOCTRINE_VERSION=~2.4.0 POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.1
  - DOCTRINE_VERSION=~2.4.0 POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.2

  - DOCTRINE_VERSION=~2.4.0 POSTGRESQL_VERSION=9.2 POSTGIS_VERSION=2.0
  - DOCTRINE_VERSION=~2.4.0 POSTGRESQL_VERSION=9.2 POSTGIS_VERSION=2.1
  - DOCTRINE_VERSION=~2.4.0 POSTGRESQL_VERSION=9.2 POSTGIS_VERSION=2.2

  - DOCTRINE_VERSION=~2.4.0 POSTGRESQL_VERSION=9.3 POSTGIS_VERSION=2.1
  - DOCTRINE_VERSION=~2.4.0 POSTGRESQL_VERSION=9.3 POSTGIS_VERSION=2.2

  - DOCTRINE_VERSION=~2.4.0 POSTGRESQL_VERSION=9.4 POSTGIS_VERSION=2.1
  - DOCTRINE_VERSION=~2.4.0 POSTGRESQL_VERSION=9.4 POSTGIS_VERSION=2.2

  - DOCTRINE_VERSION=~2.5.0 POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=1.5
  - DOCTRINE_VERSION=~2.5.0 POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.0
  - DOCTRINE_VERSION=~2.5.0 POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.1
  - DOCTRINE_VERSION=~2.5.0 POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.2

  - DOCTRINE_VERSION=~2.5.0 POSTGRESQL_VERSION=9.2 POSTGIS_VERSION=2.0
  - DOCTRINE_VERSION=~2.5.0 POSTGRESQL_VERSION=9.2 POSTGIS_VERSION=2.1
  - DOCTRINE_VERSION=~2.5.0 POSTGRESQL_VERSION=9.2 POSTGIS_VERSION=2.2

  - DOCTRINE_VERSION=~2.5.0 POSTGRESQL_VERSION=9.3 POSTGIS_VERSION=2.1
  - DOCTRINE_VERSION=~2.5.0 POSTGRESQL_VERSION=9.3 POSTGIS_VERSION=2.2

  - DOCTRINE_VERSION=~2.5.0 POSTGRESQL_VERSION=9.4 POSTGIS_VERSION=2.1
  - DOCTRINE_VERSION=~2.5.0 POSTGRESQL_VERSION=9.4 POSTGIS_VERSION=2.2

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: DOCTRINE_VERSION=~2.4.0 POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=1.5
    - php: 5.3
      env: DOCTRINE_VERSION=~2.4.0 POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.0
    - php: 5.3
      env: DOCTRINE_VERSION=~2.4.0 POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.1
    - php: 5.3
      env: DOCTRINE_VERSION=~2.4.0 POSTGRESQL_VERSION=9.1 POSTGIS_VERSION=2.2

    - php: 5.3
      env: DOCTRINE_VERSION=~2.4.0 POSTGRESQL_VERSION=9.2 POSTGIS_VERSION=2.0
    - php: 5.3
      env: DOCTRINE_VERSION=~2.4.0 POSTGRESQL_VERSION=9.2 POSTGIS_VERSION=2.1
    - php: 5.3
      env: DOCTRINE_VERSION=~2.4.0 POSTGRESQL_VERSION=9.2 POSTGIS_VERSION=2.2

    - php: 5.3
      env: DOCTRINE_VERSION=~2.4.0 POSTGRESQL_VERSION=9.3 POSTGIS_VERSION=2.1
    - php: 5.3
      env: DOCTRINE_VERSION=~2.4.0 POSTGRESQL_VERSION=9.3 POSTGIS_VERSION=2.2

    - php: 5.3
      env: DOCTRINE_VERSION=~2.4.0 POSTGRESQL_VERSION=9.4 POSTGIS_VERSION=2.1
    - php: 5.3
      env: DOCTRINE_VERSION=~2.4.0 POSTGRESQL_VERSION=9.4 POSTGIS_VERSION=2.2

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - composer self-update -q
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;

install:
  - travis_retry ./travis/install.sh $POSTGRESQL_VERSION $POSTGIS_VERSION
  - travis_retry composer require doctrine/orm:${DOCTRINE_VERSION}
  - travis_retry composer show -i

before_script:
  - travis_retry ./travis/before_script.sh $POSTGRESQL_VERSION $POSTGIS_VERSION

script:
  - phpunit -c ./travis/phpunit.travis.postgis-$POSTGIS_VERSION.xml -v --coverage-text --coverage-clover ./build/logs/clover.postgis-$POSTGIS_VERSION.xml

after_success:
  - if [ -f ./build/logs/clover.postgis-$POSTGIS_VERSION.xml ]; then travis_retry composer require satooshi/php-coveralls --no-interaction --update-with-dependencies; fi
  - if [ -f ./build/logs/clover.postgis-$POSTGIS_VERSION.xml ]; then php vendor/bin/coveralls -v --coverage_clover ./build/logs/clover.postgis-$POSTGIS_VERSION.xml; fi
